# NOTE: update this with your service name
service: twilio-service-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

environment:
  twilioAccountSID: ${env:TWILIO_ACCOUNT_SID}
  twilioAuthToken: ${env:TWILIO_AUTH_TOKEN}
  twilioPhoneNumber: ${env:TWILIO_PHONE_NUMBER}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
